blank_issues_enabled: false
contact_links:
  - name: Discord
    about: Connect on Discord
    url: https://discord.gg/abca3pDPvu

  - name: FAQ-CM7
    about: Frequently Asked Questions (CM7)
    url: https://github.com/CompactMods/CompactMachines/wiki/CM7-%E2%80%90-Frequently-Asked-Questions
