name: Data Generation

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  datagen:
    name: Data Generators
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Data Generation
        run: ./gradlew :runData
        env:
          VERSION: ${{ inputs.version }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store Built Assets
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: generated-data
          path: src/generated/resources

      - name: Store Compiled
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build